### ISSUE TITLE
CHANGELOG, please

### ISSUE THREAD

**Issue by knightq** [zakird/wkhtmltopdf_binary_gem#35]
It would be nice to know _what changes_ between two versions and _at least_ if the version number follows semantic versioning...

**Comment by k3rni** [comment]
This gem's version number is locked to the upstream binary's one. Since it does nothing else except supplying them in easily consumable form, there is little reason to provide a changelog. Pointing users to the [actual changelog](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.5) might be useful though.

**Comment by unixmonkey** [comment]
This project has a [CHANGELOG](https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/CHANGELOG) now (and has for awhile).

Thank you for the suggestion, and sorry I hadn't come around to close this until just now.
