### ISSUE TITLE
Failed to extract binary

### ISSUE THREAD

**Issue by blackham** [zakird/wkhtmltopdf_binary_gem#57]
```
Error: PDF could not be generated!
 Command Error: /var/lib/gems/2.5.0/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf:34:in `initialize': Permission denied @ rb_sysopen - /var/lib/gems/2.5.0/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf_ubuntu_18.04_amd64 (Errno::EACCES)
```

A RoR app is using wkhtmltopdf-binary to generate PDFs from a web page. It was "bundle upgrade" upgraded earlier today and I started getting this error. I was able to HACK around the error by extracting the .gz file manually:

```
cd /var/lib/gems/2.5.0/gems/wkhtmltopdf-binary-0.12.5/bin/
gunzip wkhtmltopdf_ubuntu_18.04_amd64.gz
```

I'm also going to freeze the Gemfile file for my other servers to 0.12.4. 

```
gem 'wkhtmltopdf-binary', '0.12.4'
```

* I haven't tested locking the Gemfile yet.

**Comment by Xylakant** [comment]
This happens for us as well. Application is deployed in a docker container. The reason is that the user that the application runs as doesn't have permissions to write to the target directory and fails in https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/bin/wkhtmltopdf#L34

It's a good security posture to prevent the app server from writing to the gems directory. It's probably best to unzip the file when installing the gem - there's little expectation that gems installed on one architecture would just work on a different arch when they're copied over - and the architecture won't change after installing the gem.
