### ISSUE TITLE
Can't deploy with capistrano

### ISSUE THREAD

**Issue by gregblass** [zakird/wkhtmltopdf_binary_gem#75]
Hey there!

I'm having trouble using this gem with capistrano. I'm getting this error:

`Bundler::GemNotFound: Could not find wkhtmltopdf-binary-0.12.5.4 in any of the sources`

Any clue as to what could be causing this or a way to fix it?

**Comment by unixmonkey** [comment]
I don't think there's enough information here to really tell. Are you seeing this during the `cap deploy` process, when booting up your app, or later when trying to build a PDF?

It could potentially be a networking blip between your server and Rubygems.org, if other gems were installed correctly. If that's the case, a re-deploy or `bundle install` should fix it.

If there's a timeout wrapped around the install process, it could need extending, since `wkhtmltopdf-binary` is a pretty large gem download compared to most other Ruby gems.

Please let me know what you find out.

**Comment by pedrofurtado** [comment]
@unixmonkey I think we can close this issue 🤝 We can reopen later, if more info was passed
